### ISSUE TITLE
[Proposal] Desktop Mousebind

### ISSUE THREAD

**Issue by samwhelp** [archcraft-os/archcraft-openbox#1]
# My Proposal For Desktop  Mousebind:

## Mouse left button

1. on desktop, mouse left button click to toggle show desktop. 

* [config sample](https://github.com/samwhelp/archcraft-openbox/blob/main/files/rc.xml#L1056-L1058)

``` xml
    <context name="Root">
      <mousebind button="Left" action="Press">
        <action name="ToggleShowDesktop"/>
      </mousebind>
    </context>
```

> [issue  10](https://github.com/archcraft-os/archcraft-openbox/issues/10)

## Mouse middle button

2. on desktop, mouse middle button scroll to switch workspace.

* [config sample](https://github.com/samwhelp/archcraft-openbox/blob/main/files/rc.xml#L1034-L1053)
* [config sample](https://github.com/samwhelp/archcraft-openbox/blob/main/files/rc.xml#L809-L818)

``` xml
    <context name="Desktop">
      <mousebind button="Up" action="Click">
        <action name="GoToDesktop">
          <to>previous</to>
        </action>
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="GoToDesktop">
          <to>next</to>
        </action>
      </mousebind>
    </context>
```

> [issue 11](https://github.com/archcraft-os/archcraft-openbox/issues/11)

**Comment by adi1090x** [comment]
Considered! Will be added in next release.
