### ISSUE TITLE
[Adjustment] Mouse middle scroll on desktop or frame to switch workspace

### ISSUE THREAD

**Issue by samwhelp** [archcraft-os/archcraft-openbox#11]
> Mouse middle scroll on **desktop or frame** to switch workspace

I create a [sample](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_desktop_or_frame_to_switch_workspace) for explaining this feature.

> [issue 1](https://github.com/archcraft-os/archcraft-openbox/issues/1)

### context Desktop / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_desktop_or_frame_to_switch_workspace/asset/orginal/rc.xml#L995-L1009)

``` xml
  <mouse>
    <context name="Desktop">
      <mousebind action="Click" button="A-Up">
        <action name="GoToDesktop">
          <to>previous</to>
        </action>
      </mousebind>
      <mousebind action="Click" button="A-Down">
        <action name="GoToDesktop">
          <to>next</to>
        </action>
      </mousebind>
    </context>
  </mouse>
```

### context Desktop / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_desktop_or_frame_to_switch_workspace/rc.xml#L1009-L1028)

``` xml
  <mouse>
    <context name="Desktop">
      <mousebind action="Click" button="A-Up">
        <action name="GoToDesktop">
          <to>previous</to>
        </action>
      </mousebind>
      <mousebind action="Click" button="A-Down">
        <action name="GoToDesktop">
          <to>next</to>
        </action>
      </mousebind>
      <mousebind action="Click" button="Up">
        <action name="GoToDesktop">
          <to>previous</to>
        </action>
      </mousebind>
      <mousebind action="Click" button="Down">
        <action name="GoToDesktop">
          <to>next</to>
        </action>
      </mousebind>
    </context>
  </mouse>
```

### context Frame / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_desktop_or_frame_to_switch_workspace/asset/orginal/rc.xml#L775-L791)

### context Frame / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_desktop_or_frame_to_switch_workspace/rc.xml#L791-L800)

``` xml
  <mouse>
    <context name="Frame">
      <mousebind action="Click" button="A-Up">
        <action name="GoToDesktop">
          <to>previous</to>
        </action>
      </mousebind>
      <mousebind action="Click" button="A-Down">
        <action name="GoToDesktop">
          <to>next</to>
        </action>
      </mousebind>
    </context>
  </mouse>
```

## Link

* demo / [all_enhance](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/all_enhance)

**Comment by adi1090x** [comment]
Done.
