### ISSUE TITLE
[Adjustment] Mouse middle scroll on titlebar, keep focus, when window shading

### ISSUE THREAD

**Issue by samwhelp** [archcraft-os/archcraft-openbox#12]
> Mouse middle scroll on titlebar, **keep focus**, when window shading.

I create a [sample](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_titlebar_keep_focus_when_window_shading) for explaining this feature.

### context Titlebar / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_titlebar_keep_focus_when_window_shading/asset/orginal/rc.xml#L824-L843)

``` xml
  <mouse>
    <context name="Titlebar">

      <mousebind action="Click" button="Up">
        <action name="if">
          <shaded>no</shaded>
          <then>
            <action name="Shade"/>
            <action name="FocusToBottom"/>
            <action name="Unfocus"/>
            <action name="Lower"/>
          </then>
        </action>
      </mousebind>
      <mousebind action="Click" button="Down">
        <action name="if">
          <shaded>yes</shaded>
          <then>
            <action name="Unshade"/>
            <action name="Raise"/>
          </then>
        </action>
      </mousebind>

    </context>
  </mouse>
```

### context Titlebar / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/mouse_middle_scroll_on_titlebar_keep_focus_when_window_shading/rc.xml#L824-L845)

``` xml
  <mouse>
    <context name="Titlebar">

      <mousebind action="Click" button="Up">
        <action name="if">
          <shaded>no</shaded>
          <then>
            <action name="Shade"/>
            <!--
            <action name="FocusToBottom"/>
            <action name="Unfocus"/>
            <action name="Lower"/>
            //-->
          </then>
        </action>
      </mousebind>
      <mousebind action="Click" button="Down">
        <action name="if">
          <shaded>yes</shaded>
          <then>
            <action name="Unshade"/>
            <action name="Raise"/>
          </then>
        </action>
      </mousebind>

    </context>
  </mouse>
```

## Link

* demo / [all_enhance](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/all_enhance)
* archcraft-lxde / [[Adjustment] Mouse middle scroll on titlebar, keep focus, when window shading](https://github.com/archcraft-os/archcraft-lxde/issues/2)

**Comment by adi1090x** [comment]
Done.
