### ISSUE TITLE
Issue with larger monitor

### ISSUE THREAD

**Issue by dorianim** [archcraft-os/archcraft-openbox#2]
I am using a 2560x1440 display and for some reason, the openbox toolbar and background image stay at 1080p. Windows can be placed on the whole monitor, tough.
![Screenshot_2022-03-16-04-22-22_4480x1440](https://user-images.githubusercontent.com/30153207/158625607-c2fed949-a25a-436a-8a5d-9cf683e4abb1.png)

Any Idea how to solve this?

**Comment by adi1090x** [comment]
WMs are configured that way, So if anything in not working on your device, Configure it accordingly.
