### ISSUE TITLE
Use python3 as python2 is no longer supported

### ISSUE THREAD

**Issue by yeSpud** [archcraft-os/archcraft-openbox#6]
Python2 has reached end of life and is [discouraged from being used in repositories](https://archlinux.org/news/removing-python2-from-the-repositories/).

In looking into removing python2 from my system I noticed that this package still uses it as a dependency [here](https://github.com/archcraft-os/archcraft-openbox/blob/main/PKGBUILD#L24). Can this be updated to use python3?

**Comment by yeSpud** [comment]
Looks like its used for the [ac-randr](https://github.com/archcraft-os/archcraft-openbox/blob/b6565b27c2d594a207ff4ea610283ad9cc245d2d/files/pipemenus/ac-randr) file

**Comment by adi1090x** [comment]
Fixed the issue, but py2 is needed.
