### ISSUE TITLE
[Adjustment] Drag window to move, when window maximized

### ISSUE THREAD

**Issue by samwhelp** [archcraft-os/archcraft-openbox#8]
[Adjustment] Drag window to move, when window maximized

> Drag window to move, when **window maximized**.

According [archcraft-openbox / rc.xml](https://github.com/archcraft-os/archcraft-openbox/blob/main/files/rc.xml#L804-L820)

I create a [sample](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance) for explaining this feature.

### context Titlebar / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance/asset/orginal/rc.xml#L797-L799)
* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance/asset/orginal/rc.xml#L804-L820)

``` xml
  <mouse>
    <context name="Titlebar">

      <mousebind action="Drag" button="A-Left">
        <action name="Move"/>
      </mousebind>

      <mousebind action="Drag" button="Left">
        <action name="if">
          <maximizedvertical>yes</maximizedvertical>
          <then>
            <action name="Unmaximize"/>
            <direction>vertical</direction>
            <action name="MoveResizeTo">
              <x>center</x>
              <y>current</y>
            </action>
            <action name="Move"/>
          </then>
          <else>
            <action name="Move"/>
          </else>
        </action>
      </mousebind>

    </context>
  </mouse>
```

### context Titlebar / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance/rc.xml#L815-L819)
* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance/rc.xml#L824-L839)

``` xml
  <mouse>
    <context name="Titlebar">

      <!--
      <mousebind action="Drag" button="A-Left">
        <action name="Move"/>
      </mousebind>
      //-->

      <mousebind action="Drag" button="Left">
        <action name="if">
          <maximized>yes</maximized>
          <then>
            <action name="UnmaximizeFull"/>
            <action name="MoveResizeTo">
              <x>center</x>
              <y>current</y>
            </action>
            <action name="Move"/>
          </then>
          <else>
            <action name="Move"/>
          </else>
        </action>
      </mousebind>

    </context>
  </mouse>
```

### context Frame / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance/asset/orginal/rc.xml#L780-L782)

``` xml
  <mouse>
    <context name="Frame">
      <mousebind action="Drag" button="W-Left">
        <action name="Move"/>
      </mousebind>
    </context>
  </mouse>
```

### context Frame / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_when_window_maximized_enhance/rc.xml#L780-L800)

``` xml
  <mouse>
    <context name="Frame">
      <!--
      <mousebind action="Drag" button="W-Left">
        <action name="Move"/>
      </mousebind>
      //-->
      <mousebind action="Drag" button="A-Left">
        <action name="if">
          <maximized>yes</maximized>
          <then>
            <action name="UnmaximizeFull"/>
            <action name="MoveResizeTo">
              <x>center</x>
              <y>current</y>
            </action>
            <action name="Move"/>
          </then>
          <else>
            <action name="Move"/>
          </else>
        </action>
      </mousebind>
    </context>
  </mouse>
```

## Link

* archcraft-openbox / [rc.xml](https://github.com/archcraft-os/archcraft-openbox/blob/main/files/rc.xml#L804-L820)
* archcraft-lxde / [[Adjustment] Drag window to move, when window maximized](https://github.com/archcraft-os/archcraft-lxde/issues/1)
* note-about-openbox / [drag_window_to_move_when_window_maximized_enhance](https://github.com/samwhelp/note-about-openbox/tree/gh-pages/_demo/sample/mousebind-adjustment/openbox/3.6.1/drag_window_to_move_when_window_maximized_enhance)
* demo / [all_enhance](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/all_enhance)

**Comment by adi1090x** [comment]
That's the default behavior already. Just some extra code here for config file.
