### ISSUE TITLE
[Adjustment] Drag window to move, keep shaded, when window shaded.

### ISSUE THREAD

**Issue by samwhelp** [archcraft-os/archcraft-openbox#9]
> Drag window to move, **keep shaded**, when **window shaded**.

I create a [sample](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_keep_shaded_when_window_shaded) for explaining this feature.

### context Titlebar Top Right Bottom Left TLCorner TRCorner BRCorner BLCorner / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_keep_shaded_when_window_shaded/asset/orginal/rc.xml#L860-L864)

``` xml
  <mouse>
    <context name="Titlebar Top Right Bottom Left TLCorner TRCorner BRCorner BLCorner">
      <mousebind action="Press" button="Left">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
    </context>
  </mouse>
```

### context Titlebar Top Right Bottom Left TLCorner TRCorner BRCorner BLCorner / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/blob/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/drag_window_to_move_keep_shaded_when_window_shaded/rc.xml#L860-L870)

``` xml
  <mouse>
    <context name="Titlebar Top Right Bottom Left TLCorner TRCorner BRCorner BLCorner">
      <!--
      <mousebind action="Press" button="Left">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      //-->
      <mousebind action="Press" button="Left">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
    </context>
  </mouse>
```

## Link

* note-about-openbox / [drag_window_to_move_keep_shaded_when_window_shaded](https://github.com/samwhelp/note-about-openbox/tree/gh-pages/_demo/sample/mousebind-adjustment/openbox/3.6.1/drag_window_to_move_keep_shaded_when_window_shaded)
* demo / [all_enhance](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-openbox/2022-09-16/all_enhance)

**Comment by adi1090x** [comment]
Adjusted! (Sorry, i don't even know why the PR were closed, perhaps conflicts)
